env:
  global:
  - REFTEST_IGNORE_TRANSIENT=YES
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
matrix:
  include:
    - sudo: false
      dist: bionic
      language: python
      python: "3.7"
      env: BRBASE=7.0 BRPVXS=devel PROF=latest
      install: ./.ci/travis-linux-prepare.sh
      script: ./.ci/travis-linux-build.sh

    - sudo: false
      dist: trusty
      language: python
      python: "2.7"
      env: BRBASE=7.0 BRPVXS=devel PROF=deb9
      install: ./.ci/travis-linux-prepare.sh
      script: ./.ci/travis-linux-build.sh

    - sudo: false
      dist: trusty
      language: python
      python: "2.7"
      env: BRBASE=3.15 BRPVXS=devel PROF=deb8
      install: ./.ci/travis-linux-prepare.sh
      script: ./.ci/travis-linux-build.sh
